# Generated by Django 2.1.3 on 2019-02-27 05:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('zhcp', '0003_auto_20190227_1336'),
    ]

    operations = [
        migrations.AddField(
            model_name='application',
            name='score',
            field=models.IntegerField(default=2),
            preserve_default=False,
        ),
    ]
