# Generated by Django 2.1.3 on 2019-02-27 05:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('zhcp', '0004_application_score'),
    ]

    operations = [
        migrations.CreateModel(
            name='Activity',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20)),
                ('score', models.IntegerField()),
                ('detail', models.TextField(blank=True, max_length=300)),
                ('create_time', models.DateTimeField(auto_now_add=True)),
                ('student_id', models.ManyToManyField(blank=True, to='zhcp.Users')),
            ],
            options={
                'db_table': 'Activity',
                'ordering': ['id'],
            },
        ),
    ]
