# Generated by Django 2.1.3 on 2019-02-27 02:31

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Application',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('student_id', models.CharField(max_length=12)),
                ('name', models.CharField(max_length=20)),
                ('detail', models.TextField(max_length=300)),
                ('status', models.BooleanField(default=False)),
                ('captain_id', models.CharField(max_length=12)),
                ('create_time', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Users',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('student_id', models.CharField(max_length=12)),
                ('name', models.CharField(max_length=20)),
                ('password', models.CharField(max_length=20)),
                ('identity', models.CharField(default='student', max_length=20)),
            ],
            options={
                'db_table': 'Users',
                'ordering': ['id'],
            },
        ),
    ]
