# Generated by Django 2.1.3 on 2019-02-27 05:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('zhcp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='application',
            name='captain_id',
            field=models.CharField(blank=True, max_length=12),
        ),
        migrations.AlterField(
            model_name='application',
            name='detail',
            field=models.TextField(blank=True, max_length=300),
        ),
        migrations.AlterField(
            model_name='application',
            name='student_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='zhcp.Users'),
        ),
    ]
