# Generated by Django 2.1.3 on 2019-02-27 05:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('zhcp', '0002_auto_20190227_1309'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='application',
            options={'ordering': ['id']},
        ),
        migrations.AlterModelTable(
            name='application',
            table='Application',
        ),
    ]
