# Generated by Django 2.1.3 on 2019-03-03 07:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('zhcp', '0007_auto_20190303_1503'),
    ]

    operations = [
        migrations.AlterField(
            model_name='activity',
            name='student_id',
            field=models.ManyToManyField(blank=True, to='zhcp.Users'),
        ),
    ]
