# Generated by Django 2.1.3 on 2019-03-06 06:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('zhcp', '0009_auto_20190303_2206'),
    ]

    operations = [
        migrations.AddField(
            model_name='application',
            name='change_time',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
