# Generated by Django 2.1.3 on 2019-03-15 07:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('zhcp', '0011_auto_20190315_1510'),
    ]

    operations = [
        migrations.AlterField(
            model_name='users',
            name='class_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='zhcp.Classes'),
        ),
    ]
