# Generated by Django 2.1.3 on 2019-04-25 12:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('zhcp', '0013_daynumber_userip_visitnumber'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='daynumber',
            options={'ordering': ['day']},
        ),
        migrations.AlterModelOptions(
            name='userip',
            options={'ordering': ['id']},
        ),
        migrations.AddField(
            model_name='userip',
            name='student_id',
            field=models.CharField(default='未知账户', max_length=12),
        ),
    ]
